In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:] #grabbing everything _beyond_ index 5!

array([ 5,  6,  7,  8,  9, 10])

# NumPy arrays' broadcasting

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0, 11)
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Beware! Since `slice_of_arr` was modified, `arr` changed as well! The original array reflects the sliced array's changes. 

This is due to memory optimalization design decisions to avoid issues when working with huge data. NumPy doesn't automatically create copies of arrays, it works with references.

If you want to work with a copy of an array instead of a reference, you must use the `copy()` function.

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 15

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

# Indexing and bracket notations

In [27]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][0] #double bracket notation

5

In [34]:
arr_2d[0]

array([ 5, 10, 15])

In [35]:
arr_2d[1][1]

25

In [37]:
arr_2d[0, 0] #comma - single bracket notation

5

In [39]:
arr_2d[2, 1] #usually less prone to error

40

In [41]:
arr_2d[:2, 1:] #slice notation

array([[10, 15],
       [25, 30]])

#### The slice notation says: `[:2,1:]`
_"Grab evetyhging up to row 2, then grab from column 1 onwards."_

_"Take the whole matrix up until and excluding the 3rd row, and then take all columns after and including the 2nd."_

# Conditional selection

In [42]:
arr = np.arange(1, 11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr > 5

In [46]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

Getting a NumPy array and using a comparison operator on it will return a boolean array of the same size, where all values will be True or False as a result of the expression for each values of the original array.

Then you can use the resulting boolean array to index or conditionally select elements from the original array where the boolean array's elements happen to be true.

In [48]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

It's a freaking `filter()` with lambda notation nicely tucked under the hood, how awesome is it!

In [49]:
arr_2d = np.arange(50).reshape(5, 10)

In [50]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])