In [2]:
###NumPy Arrays
import numpy as np

In [7]:
my_list = [1, 2, 3]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.57840532, 0.62946967, 0.78101914, 0.7450725 , 0.1201266 ])

In [25]:
np.random.rand(5, 5)

array([[0.20745686, 0.21654774, 0.90574893, 0.60841712, 0.28909228],
       [0.23156788, 0.06126383, 0.94473746, 0.71898592, 0.61738248],
       [0.13160082, 0.46201534, 0.45725922, 0.94057097, 0.79189811],
       [0.49231632, 0.48114664, 0.21009316, 0.91579639, 0.62256609],
       [0.17143255, 0.83303538, 0.10815372, 0.48648179, 0.03096679]])

In [28]:
np.random.randn(2)

array([ 1.50032478, -0.59849423])

In [29]:
np.random.randint(1, 100)

25

In [3]:
np.random.randint(1, 100, 10)

array([26, 26, 94, 42, 84, 87,  2,  8, 81, 43])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0, 50, 10)

In [34]:
ranarr

array([49, 12,  1, 30,  9,  9,  8, 35, 10,  1])

In [35]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

49

In [37]:
ranarr.min()

1

In [38]:
ranarr.argmax()

0

In [39]:
ranarr.argmin()

2

In [41]:
arr = arr.reshape(5, 5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')